name: Continuous Integration

# This action works with pull requests and pushes
# This action works with ALL branches
on:
  push:
  pull_request:

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 7
          run_install: false
      - name: Update Lockfile and Install Dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install
      - name: ESLint
        run: pnpm run lint-total
      - name: Prettier
        run: pnpm run prettier-check
      - name: TypeScript Compiler
        run: npx tsc
        # Run Next Lint + TSC + BUILD
      - name: Next.js Build
        run: pnpm run build
