name: Playwright Tests
on:
  push:
  pull_request:

env:
  ACCOUNT_MAIL_TEST: ${{ secrets.ACCOUNT_MAIL_TEST }}
  ACCOUNT_PASSWORD_TEST: ${{ secrets.ACCOUNT_PASSWORD_TEST }}
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  playwright_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
          run_install: false
      # https://docs.npmjs.com/cli/v8/commands/npm-ci
      # pnpm install --frozen-lockfile is the equivalent of npm-ci
      - name: Update Lockfile and Install Dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
